version: "3"

services:
  ftp:
    image: stilliard/pure-ftpd
    environment:
    - PUBLICHOST=localhost
    - FTP_USER_NAME=user
    - FTP_USER_PASS=password
    - FTP_USER_HOME=/home/user
    ports:
    - "2221:21"
    - "30000-30009:30000-30009"
    volumes:
    - ./docker/ftp:/home/user
