name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.3
        with:
          lein: '2.11.1'

      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: cljdeps-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-

      - name: Run tests
        run: lein with-profile +1.9:+1.10:+1.11 test
